#!/usr/bin/env python3
import argparse
import pathlib
import re
from typing import Iterable, List, Set, Tuple


RULE_RE = re.compile(r"^(DOMAIN|DOMAIN-SUFFIX),([^,]+),")


def parse_rules(path: pathlib.Path) -> Tuple[Set[str], Set[str]]:
    domains: Set[str] = set()
    suffixes: Set[str] = set()
    in_rules = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            in_rules = line.lower() == "[rule]"
            continue
        if not in_rules:
            continue
        match = RULE_RE.match(line)
        if not match:
            continue
        kind, value = match.group(1), match.group(2).strip()
        if kind == "DOMAIN":
            domains.add(value)
        elif kind == "DOMAIN-SUFFIX":
            suffixes.add(value)
    return domains, suffixes


def collect_rules(files: Iterable[pathlib.Path]) -> Tuple[List[str], List[str]]:
    domains: Set[str] = set()
    suffixes: Set[str] = set()
    for path in files:
        file_domains, file_suffixes = parse_rules(path)
        domains.update(file_domains)
        suffixes.update(file_suffixes)
    return sorted(domains), sorted(suffixes)


def render_linux_script(domains: List[str], suffixes: List[str]) -> str:
    domain_lines = "\n".join(f"  \"{d}\"" for d in domains)
    suffix_lines = "\n".join(f"  \"{s}\"" for s in suffixes)
    return f"""#!/usr/bin/env bash
set -euo pipefail

MODE="${{1:-enforce}}"

DOMAINS=(
{domain_lines}
)

SUFFIXES=(
{suffix_lines}
)

ALLOW_SET_V4="firewall_allow_v4"
ALLOW_SET_V6="firewall_allow_v6"
CHAIN="FIREWALL_ALLOW"
DNSMASQ_CONF="/etc/dnsmasq.d/firewall-allow.conf"

require_cmd() {{
  command -v "$1" >/dev/null 2>&1 || {{
    echo "Missing required command: $1" >&2
    exit 1
  }}
}}

require_cmd ipset
require_cmd iptables

if command -v ip6tables >/dev/null 2>&1; then
  HAVE_IP6=1
else
  HAVE_IP6=0
fi

ipset create "$ALLOW_SET_V4" hash:ip -exist
if [[ "$HAVE_IP6" -eq 1 ]]; then
  ipset create "$ALLOW_SET_V6" hash:ip family inet6 -exist
fi

resolve_domain() {{
  local domain="$1"
  getent ahosts "$domain" | awk '{{print $1}}' | sort -u
}}

if [[ "$MODE" == "--dnsmasq" ]]; then
  require_cmd systemctl
  {{
    echo "# Generated by generate_linux_firewall.py"
    for d in "${{DOMAINS[@]}}"; do
      echo "ipset=/${{d}}/${{ALLOW_SET_V4}},${{ALLOW_SET_V6}}"
    done
    for s in "${{SUFFIXES[@]}}"; do
      echo "ipset=/${{s}}/${{ALLOW_SET_V4}},${{ALLOW_SET_V6}}"
    done
  }} | sudo tee "$DNSMASQ_CONF" >/dev/null
  sudo systemctl restart dnsmasq
else
  for d in "${{DOMAINS[@]}}"; do
    while read -r ip; do
      if [[ "$ip" == *:* ]]; then
        [[ "$HAVE_IP6" -eq 1 ]] && ipset add "$ALLOW_SET_V6" "$ip" -exist
      else
        ipset add "$ALLOW_SET_V4" "$ip" -exist
      fi
    done < <(resolve_domain "$d")
  done
  if [[ "${{#SUFFIXES[@]}}" -gt 0 ]]; then
    echo "Warning: DOMAIN-SUFFIX rules require DNS-based ipset. Re-run with --dnsmasq." >&2
  fi
fi

iptables -N "$CHAIN" 2>/dev/null || true
iptables -F "$CHAIN"
iptables -C OUTPUT -j "$CHAIN" 2>/dev/null || iptables -A OUTPUT -j "$CHAIN"
iptables -A "$CHAIN" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A "$CHAIN" -o lo -j ACCEPT
iptables -A "$CHAIN" -p udp --dport 53 -j ACCEPT
iptables -A "$CHAIN" -p tcp --dport 53 -j ACCEPT
iptables -A "$CHAIN" -m set --match-set "$ALLOW_SET_V4" dst -j ACCEPT

if [[ "$HAVE_IP6" -eq 1 ]]; then
  ip6tables -N "$CHAIN" 2>/dev/null || true
  ip6tables -F "$CHAIN"
  ip6tables -C OUTPUT -j "$CHAIN" 2>/dev/null || ip6tables -A OUTPUT -j "$CHAIN"
  ip6tables -A "$CHAIN" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  ip6tables -A "$CHAIN" -o lo -j ACCEPT
  ip6tables -A "$CHAIN" -p udp --dport 53 -j ACCEPT
  ip6tables -A "$CHAIN" -p tcp --dport 53 -j ACCEPT
  ip6tables -A "$CHAIN" -m set --match-set "$ALLOW_SET_V6" dst -j ACCEPT
fi

if [[ "$MODE" == "enforce" ]]; then
  iptables -A "$CHAIN" -j REJECT
  if [[ "$HAVE_IP6" -eq 1 ]]; then
    ip6tables -A "$CHAIN" -j REJECT
  fi
fi

echo "Linux firewall rules applied (mode: $MODE)."
"""


def build_fqdns(domains: List[str], suffixes: List[str]) -> List[str]:
    fqdns: Set[str] = set(domains)
    for suffix in suffixes:
        fqdns.add(suffix)
        fqdns.add(f"*.{suffix}")
    return sorted(fqdns)


def render_windows_script(domains: List[str], suffixes: List[str], expected_major: int) -> str:
    fqdns = build_fqdns(domains, suffixes)
    fqdn_lines = "\n".join(f"    \"{fqdn}\"" for fqdn in fqdns)
    return f"""#requires -version {expected_major}.0
[CmdletBinding()]
param(
    [ValidateSet('Enforce', 'Allow')]
    [string]$Mode = 'Enforce'
)

$expectedMajor = {expected_major}
if ($PSVersionTable.PSVersion.Major -ne $expectedMajor) {{
    Write-Error "This script requires PowerShell {expected_major}.x."
    exit 1
}}

$ErrorActionPreference = 'Stop'

Import-Module NetSecurity -ErrorAction Stop

$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent() `
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {{
    Write-Error "Run this script as Administrator."
    exit 1
}}

$group = 'SurgeFirewall'
$rulePrefix = 'SurgeAllow'
$fqdns = @(
{fqdn_lines}
)

Get-NetFirewallRule -Group $group -ErrorAction SilentlyContinue | Remove-NetFirewallRule

New-NetFirewallRule -DisplayName "$rulePrefix-DNS-UDP" -Group $group `
    -Direction Outbound -Action Allow -Protocol UDP -RemotePort 53 | Out-Null
New-NetFirewallRule -DisplayName "$rulePrefix-DNS-TCP" -Group $group `
    -Direction Outbound -Action Allow -Protocol TCP -RemotePort 53 | Out-Null

$chunkSize = 50
for ($i = 0; $i -lt $fqdns.Count; $i += $chunkSize) {{
    $end = [Math]::Min($i + $chunkSize - 1, $fqdns.Count - 1)
    $chunk = $fqdns[$i..$end]
    New-NetFirewallRule -DisplayName "$rulePrefix-FQDN-$i" -Group $group `
        -Direction Outbound -Action Allow -RemoteFqdn $chunk | Out-Null
}}

if ($Mode -eq 'Enforce') {{
    Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultOutboundAction Block | Out-Null
}} else {{
    Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultOutboundAction Allow | Out-Null
}}

Write-Host "Windows firewall rules applied (mode: $Mode)."
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Linux and Windows firewall scripts from Surge v5 modules."
    )
    parser.add_argument(
        "--ios-dir",
        default="ios",
        help="Directory containing Surge v5 .sgmodule files (default: ios)",
    )
    parser.add_argument(
        "--output",
        default="linux/apply-firewall.sh",
        help="Output shell script path (default: linux/apply-firewall.sh)",
    )
    parser.add_argument(
        "--windows-dir",
        default="windows",
        help="Directory for generated PowerShell scripts (default: windows)",
    )
    args = parser.parse_args()

    ios_dir = pathlib.Path(args.ios_dir)
    if not ios_dir.exists():
        raise SystemExit(f"Missing iOS directory: {ios_dir}")

    files = sorted(ios_dir.glob("*.sgmodule"))
    if not files:
        raise SystemExit(f"No .sgmodule files found in {ios_dir}")

    domains, suffixes = collect_rules(files)
    output_path = pathlib.Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_linux_script(domains, suffixes), encoding="utf-8", newline="\n"
    )
    print(f"Wrote {output_path}")

    windows_dir = pathlib.Path(args.windows_dir)
    windows_dir.mkdir(parents=True, exist_ok=True)
    ps6_path = windows_dir / "apply-firewall-ps6.ps1"
    ps7_path = windows_dir / "apply-firewall-ps7.ps1"
    ps6_path.write_text(
        render_windows_script(domains, suffixes, expected_major=6),
        encoding="utf-8",
        newline="\n",
    )
    ps7_path.write_text(
        render_windows_script(domains, suffixes, expected_major=7),
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {ps6_path}")
    print(f"Wrote {ps7_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
