#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-enforce}"

DOMAINS=(
  "account.microsoft.com"
  "device.login.microsoftonline.com"
  "docs.microsoft.com"
  "download.microsoft.com"
  "download.windowsupdate.com"
  "enrollment.manage.microsoft.com"
  "enterpriseenrollment.manage.microsoft.com"
  "graph.microsoft.com"
  "graph.windows.net"
  "hosting.portal.azure.net"
  "learn.microsoft.com"
  "login.live.com"
  "login.microsoft.com"
  "login.microsoftonline.com"
  "login.windows.net"
  "manage.microsoft.com"
  "management.azure.com"
  "officecdn.microsoft.com"
  "portal.azure.com"
  "portal.manage.microsoft.com"
  "reactblade.portal.azure.net"
  "support.microsoft.com"
  "update.microsoft.com"
)

SUFFIXES=(
  "aaplimg.com"
  "aadcdn.microsoftonline-p.com"
  "apple-cloudkit.com"
  "apple-dns.net"
  "apple-mapkit.com"
  "apple.com"
  "apple.com.cn"
  "apple.news"
  "applemusic.com"
  "appstore.com"
  "azure.com"
  "bing.com"
  "bing.net"
  "cdn-apple.com"
  "cdn.office.net"
  "icloud-content.com"
  "icloud.com"
  "itunes.com"
  "live.com"
  "mac.com"
  "me.com"
  "microsoft.com"
  "microsoftonline.com"
  "microsoftstore.com"
  "microsoftupdate.com"
  "msauth.net"
  "msauthimages.net"
  "msftauth.net"
  "msftauthimages.net"
  "msn.com"
  "mzstatic.com"
  "office.com"
  "office365.com"
  "outlook.com"
  "skype.com"
  "surface.com"
  "windows.com"
  "windowsupdate.com"
  "xbox.com"
  "xboxlive.com"
)

ALLOW_SET_V4="firewall_allow_v4"
ALLOW_SET_V6="firewall_allow_v6"
CHAIN="FIREWALL_ALLOW"
DNSMASQ_CONF="/etc/dnsmasq.d/firewall-allow.conf"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

require_cmd ipset
require_cmd iptables

if command -v ip6tables >/dev/null 2>&1; then
  HAVE_IP6=1
else
  HAVE_IP6=0
fi

ipset create "$ALLOW_SET_V4" hash:ip -exist
if [[ "$HAVE_IP6" -eq 1 ]]; then
  ipset create "$ALLOW_SET_V6" hash:ip family inet6 -exist
fi

resolve_domain() {
  local domain="$1"
  getent ahosts "$domain" | awk '{print $1}' | sort -u
}

if [[ "$MODE" == "--dnsmasq" ]]; then
  require_cmd systemctl
  {
    echo "# Generated by generate_linux_firewall.py"
    for d in "${DOMAINS[@]}"; do
      echo "ipset=/${d}/${ALLOW_SET_V4},${ALLOW_SET_V6}"
    done
    for s in "${SUFFIXES[@]}"; do
      echo "ipset=/${s}/${ALLOW_SET_V4},${ALLOW_SET_V6}"
    done
  } | sudo tee "$DNSMASQ_CONF" >/dev/null
  sudo systemctl restart dnsmasq
else
  for d in "${DOMAINS[@]}"; do
    while read -r ip; do
      if [[ "$ip" == *:* ]]; then
        [[ "$HAVE_IP6" -eq 1 ]] && ipset add "$ALLOW_SET_V6" "$ip" -exist
      else
        ipset add "$ALLOW_SET_V4" "$ip" -exist
      fi
    done < <(resolve_domain "$d")
  done
  if [[ "${#SUFFIXES[@]}" -gt 0 ]]; then
    echo "Warning: DOMAIN-SUFFIX rules require DNS-based ipset. Re-run with --dnsmasq." >&2
  fi
fi

iptables -N "$CHAIN" 2>/dev/null || true
iptables -F "$CHAIN"
iptables -C OUTPUT -j "$CHAIN" 2>/dev/null || iptables -A OUTPUT -j "$CHAIN"
iptables -A "$CHAIN" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A "$CHAIN" -o lo -j ACCEPT
iptables -A "$CHAIN" -p udp --dport 53 -j ACCEPT
iptables -A "$CHAIN" -p tcp --dport 53 -j ACCEPT
iptables -A "$CHAIN" -m set --match-set "$ALLOW_SET_V4" dst -j ACCEPT

if [[ "$HAVE_IP6" -eq 1 ]]; then
  ip6tables -N "$CHAIN" 2>/dev/null || true
  ip6tables -F "$CHAIN"
  ip6tables -C OUTPUT -j "$CHAIN" 2>/dev/null || ip6tables -A OUTPUT -j "$CHAIN"
  ip6tables -A "$CHAIN" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  ip6tables -A "$CHAIN" -o lo -j ACCEPT
  ip6tables -A "$CHAIN" -p udp --dport 53 -j ACCEPT
  ip6tables -A "$CHAIN" -p tcp --dport 53 -j ACCEPT
  ip6tables -A "$CHAIN" -m set --match-set "$ALLOW_SET_V6" dst -j ACCEPT
fi

if [[ "$MODE" == "enforce" ]]; then
  iptables -A "$CHAIN" -j REJECT
  if [[ "$HAVE_IP6" -eq 1 ]]; then
    ip6tables -A "$CHAIN" -j REJECT
  fi
fi

echo "Linux firewall rules applied (mode: $MODE)."
